---
title: "CV"
editor: visual
---

    EDUCATION

    A. Doctorate in Medicine, Iran University of Medical Sciences (IUMS), Tehran. Iran, 2006

    TRAINING

    11. Value of Imaging through Comparative Effectiveness (VOICE), Oak Brook, IL, USA, 2019
    10. NIH Grant Writing, course number 101, Chicago, IL, USA, 2019
    9. HealthMeasures measurement systems (PROMIS®, Neuro-QoL, NIH Toolbox® and ASCQ-Me), Chicago, IL, USA, 2016
    8. MRI Physics and Fundamentals, UCSD, San Diego, USA, 2012
    7. Multilevel Modeling, Deputy of Research, IUMS, Iran, 2010
    6. Applied STATA, Iran Epidemiologists Association, Iran, 2010
    5. Qualitative Studies, Medical Student Research Committee, IUMS, Iran, 2009
    4. Research in Medical Education, Ministry of Health, Iran, 2008
    3. Review Manager Software, Medical Student Research Committee, IUMS, Iran, 2007
    2. Survival Analysis, Medical Student Research Committee, IUMS, Iran, 2002
    1. Design and Analysis in Randomized Controlled Clinical Trials, Semnan University of Medical Sciences, Iran, 2000

    LICENSURE / CERTIFICATION

    A. Iran Medical License, No: 111568

    ACADEMIC APPOINTMENTS

    5. Research Fellow, Neurological Surgery and Radiology Department, NU, Chicago, IL, 2016
    4. Research Fellow, Radiology Department, UHCMC, Cleveland, OH, 2014
    3. Research Fellow, Medical Educational Development Center (MEDC), IUMS, Tehran, Iran, 2013
    2. Research Fellow, Radiology Department, UCSD, San Diego, CA, 2012
    1. Research Fellow, Cardiac CT-MRI Department, Shahid Rajaei Medical and Research Center, Tehran, Iran, 2011

    HONORS AND AWARDS

    A. International/National/Regional

    10. Kuo York Chynn Neuroradiology Research Award, RSNA, Chicago, IL, USA, 2019 (as co-author)
    9. Trainee Research Prize, RSNA, Chicago, IL, USA, 2019 (as co-author)
    8. NYU Langone Health Trainee Award, VOICE program, Oak Brook, IL, USA, 2019
    7. Trainee Travel Grant Award, San Diego, CA, SVIN, USA, 2018 (as co-author)
    6. Kuo York Chynn Neuroradiology Research Award, RSNA, Chicago, IL, USA, 2016
    5. National Student Researcher of the Year, Deputy of Research of Ministry of Health, Iran, 2005
    4. 1st place Best Oral Presentation, 3rd Young Medics' International Conference, Yerevan, Armenia, 2005 (as co-author)
    3. 3rd place Best Oral Presentation, 4th National Medical Students' Congress, Hamedan, Iran, 2002
    2. 2nd place Best Poster Presentation, 2nd National Medical Students' Congress, Gorgan, Iran, 2001 B. University
    1. Gifted and Talented Student of the Year, IUMS, Tehran, Iran, 2004

    INSTITUTIONAL SERVICE (Committees, Councils, Task Forces)

    4. Health System Research (HSR) Council, Jahrom University of Medical Sciences (JUMS), Jahrom, Iran, 2007
    3. Supervisor of Medical Student Research Committee, JUMS, Jahrom, Iran, 2007
    2. Head of Student Research Council, IUMS, Tehran, Iran, 2002
    1. Head of Research Division of Medical Student Research Committee, IUMS, Tehran, Iran, 2002

    PARTICIPATION IN PROFESSIONAL SOCIETIES AND EXTRAMURAL ORGANIZATIONS

    A. Professional Society Memberships

    14. American of College Radiology (ACR)
    13. American Roentgen Ray Society (ARRS)
    12. Radiological Society of North America (RSNA)
    11. Association of University Radiologists (AUR)
    10. Society of NeuroInterventional Surgery (SNIS)
    9. American Society of NeuroRadiology (ASNR)
    8. American Society of Spine Radiology (ASSR)
    7. American Heart Association/American Stroke Association (AHA/ASA)
    6. North American Iranian Radiological Society (NAIRS)
    5. Iran Medical Council (IMC)
    4. Iranian Sport Medicine Association (ISMA) B. Leadership and Service (leadership positions held, committee service, etc.)
    3. Scientific Committee Member and Referee at 5th National Medical Students Annual Conference, Iran, 2008
    2. Scientific Committee Member and Referee at 9th National Medical Students Annual Conference, Iran, 2004

    C. Volunteer

    1. RAD-AID

    EDITORIAL AND MANUSCRIPT REVIEW RESPONSIBILITIES

    A. Journal Reviewer
    12. PLoS One
    11. Human and Experimental Toxicology
    10. Medical Science Monitor
    9. The Journal of Psychology
    B. Mentored Reviewer
    8. Journal of NeuroInterventional Surgery (JNIS)
    7. Journal of Neurosurgery (JNS)
    6. International Journal of Stroke (IJS)
    5. Neurosurgery
    4. World Neurosurgery
    3. Neurology
    2. Neurocritical Care
    1. Journal of Neurology, Neurosurgery, and Psychiatry (JNNP)

    GRANT REVIEW RESPONSIBILITIES
    2. Research Council, JUMS, Jahrom, Iran, 2008
    1. Student Research Council, IUMS, Tehran, Iran, 2004

    GRANT AWARDS AND CLINICAL TRIALS

    A. Past

    1. Agency: Society of NeuroInterventional Surgery (SNIS)-Joe Niekro Research
    Grant Title: Diagnosis of acute hemorrhagic and ischemic stroke using Thermoencephalography
    Principal Investigator: Ansari SA
    Role on project: Co-investigator
    Percent effort: 20%
    Direct costs per year: 20,000 USD Total costs for project period: 20,000 USD
    Project period: 1 Year

    INVITED LECTURES

    A. International/National

    12. Best Evidence in Medical Education, 10th National Medical Education Congress, Tehran, Iran, 2010
    11. Principles of Questionnaire Designing (National Workshop), Tehran, Iran, 2002
    10. Design and Analysis in Analytic-Observational Studies (National Workshop), Tehran, Iran, 2002

    B. Local

    9. Medical Research Methodology, Firoozgar Teaching Hospital, Tehran, Iran, 2008
    8. Sampling Methods and Sample Size Calculations, JUMS, Jahrom, Iran, 2008
    7. Biostatistics and Applied SPSS, JUMS, Jahrom, Iran, 2008
    6. Scientific Writing, JUMS, Jahrom, Iran, 2008
    5. Search Strategy and Databases in Medical Research, JUMS, Jahrom, Iran, 2007
    4. Medical Research Methodology, JUMS, Jahrom, Iran (3 Courses), 2007
    3. Biostatistics and Applied SPSS, IUMS, Tehran, Iran (5 Courses), 2001-2006
    2. Scientific Writing, IUMS, Tehran, Iran, 2000
    1. Medical Research Methodology, IUMS, Tehran, Iran (14 Courses), 2000-2005

    PUBLICATIONS AND SCHOLARLY WORK

    A. Peer-reviewed Articles

    30. Golnari P, Nazari P, Hurley MC, Shaibani A, Ansari SA, Potts MB, Jahromi BS. Continued dominance of carotid endarterectomy over stenting in the United States: Volumes, outcomes, and complications from the National Inpatient Sample (1997-2015). World Neurosurg. 2022;163:e238-e252

    29. Nazari P, Golnari P, Ansari SA, Cantrell RD, Potts MB, Jahromi BS. Unplanned Readmission After Carotid Stenting versus Endarterectomy: Analysis of the United States Nationwide Readmission Database. J NeuroInterv Surg. 2022 Feb 15;neurintsurg-2021-018523

    27. Nazari P, Golnari P, Hurley MC, Potts MB, Shaibani A, Ansari SA, Jahromi BS. Carotid Stenting Without Cerebral Protection Increases Major Adverse Events: Analysis of the National Surgical Quality Improvement Program. AJNR Am J Neuroradiol. 2021;42(7):1264-1269

    26. Potts MB, Abdalla R, Golnari P, Sukumaran M, Palmer A, Hurley MC, Shaibani A, Jahromi BS, Ansari SA. Analysis of mechanical thrombectomy for acute ischemic stroke on nights and weekends versus weekdays at Comprehensive Stroke Centers. J Stroke Cerebrovasc Dis. 2021;30(4):1-9

    25. Golnari P, Nazari P, Ansari SA, Hurley MC, Shaibani A, Potts MB, Jahromi BS. Endovascular Thrombectomy after Large Vessel Ischemic Stroke: Nationwide Utilization, Outcomes and Readmissions. Radiology. 2021;299(1):179-189-Editor’s Choice

    24. Mansoori B, Golnari P, Sharifi A, Khoshpouri P, Chalian H, Herrmann K, Chalian M. Ultrasonography Training in Radiology Residency Programs: A National Survey. J Ultrasound Med. 2021;40(4):731-740

    23. Nazari P, Golnari P, Sukumaran M, Shaibani A, Hurley MC, Ansari SA, Potts MB, Jahromi BS. Spontaneous Thrombosis of a Middle Meningeal Arteriovenous Fistula with Subsequent Pseudoaneurysm Formation: Case Report and Review of Literature. Neurosurgery Open. 2020;1(3):1-9

    22. Golnari P, Nazari P, Garcia RM, Weiss H, Shaibani A, Hurley MC, Ansari SA, Potts MB, Jahromi BS. Volumes, outcomes, and complications after surgical versus endovascular treatment of aneurysms in the United States (1993-2015): continued evolution versus steady state after more than 2 decades of practice. J Neurosurg. 2020;134(3):848-861-Editor’s Choice

    21. Kalluri AG, Sukumaran M, Nazari P, Golnari P, Ansari SA, Hurley MC, Shaibani A, Jahromi BS, Potts MB. Retrospective review of 290 small carotid cave aneurysms over 17 years. J Neurosurg. 2020;133(5):1473-1477

    20. Golnari P, Ansari SA, Shaibani A, Hurley MC, Potts MB, Kohler ME, Sugrue PA, Jahromi BS. Intradural Extramedullary Cavernous Malformation with Extensive Superficial Siderosis of the Neuraxis: Case Report and Review of Literature. Surg Neurol Int. 2017;8(1):109-113

    19. Sodagari F, Golnari P. Clinical internship for radiology: to be, or not to be. Acad Radiol. 2016;23(8):1069

    18. Golnari P, Forsberg D, Rosipko B, Sunshine JL. Online Error Reporting for Managing Quality Control within Radiology. J Digit Imaging. 2015;29(3):301-308

    17. Golnari P, Sodagari F, Baradaran HR. Quality of Published Iranian Medical Education Research Studies: A Systematic Review. Med J Islam Repub Iran. 2014;28(79):1-10

    16. Sanati H, Zahedmehr A, Firouzi A, Salehi N, Maadani M, Shakerian F, Kiani R, Golnari P, Parchami-Ghazaee S, Peighambari M. Coronary Flow Assessment in Unstable Angina/non-ST- segment Elevation Myocardial Infarction Patients via Thrombolysis in Myocardial Infarction Frame Count in Angiography. Res Cardiovasc Med. 2013;2(2):95-98

    15. Alizadeh-Sani Z, Madadi Sh, Sadeghpour A, Khajali Z, Golnari P, Kiavar M. Cardiac MRI in A Patient with Coincident Left Ventricular Non-Compaction and Hypertrophic Cardiomyopathy. J Tehran Heart Cent. 2011;6(4):214-216

    14. Poormoghim H, Shekarabi M, Golnari P, Yazdipoor N, Nozari M, Farjam-Nia A, Falak R. Evaluation of the Diagnostic Accuracy of Anti-Citrulline Antibody in Rheumatoid Arthritis Patients and Its Comparison with Other Rheumatic Disorders and Normal Individuals. Razi J Med Sci. 2009;16(62):89-98

    13. Otukesh H, Hoseini R, Golnari P, Fereshtehnejad SM, Zamanfar D, Hooman N, Tabarroki A. Short-Term and Long-Term Outcome of Hemolytic Uremic Syndrome in Iranian Children. J Nephrol 2008;21(5):694-703

    12. Nickavar A, Golnari P, Seddigh N. Determination of Birth Indices of Healthy Neonates. Acta Medica Iranica. 2007;45(6):469-472

    11. Razzaghy-Azar M, Moghimi A, Sadigh N, Montazer M, Golnari P, Zahedi-Shoolami L, Van Buuren S, Mohammad-Sadeghi H, Zangeneh-Kazemi A, Fereshtehnejad SM. Age of Puberty in Iranian Girls Living in Tehran. Ann Hum Biol. 2006;33(5-6):628-633

    10. Razzaghy-Azar M, Moghimi A, Montazer M, Sadeghi HM, Golnari P, Sadigh N, Ossivand S, Fereshtehnejad SM, Shoolami LZ, Pour NE. Cross-Sectional Reference Values for Height, Weight and Body Mass Index of School Children Living in Tehran, Iran. Ann Hum Biol. 2006;33(4):471-479

    9.  Otukesh H, Basiri A, Simfroosh N, Hoseini R, Sharifian M, Sadigh N, Golnari P, Rezai M, Fereshtenejad M. Outcome of Pediatric Renal Transplantation in Labafi Nejad Hospital, Tehran, Iran. Pediatr Nephrol. 2006;21(10):1459-1463

    8.  Razzaghi Azar M, Moghimi A, Montazer M, Mohammad Sadeghi H, Golnari P, Sedigh N, Ossivand S, Fereshtehnezhad M, Zahedi Shulami L, Ebrahimpour N, Zanganeh Kazemi A. Evaluation of Height, Weight and BMI (Body Mass Index) in Healthy 6-17-year-old Schoolgirls and 6-15-year-old Schoolboys, Tehran. Razi J Med Sci. 2006;13(51):115-129

    7.  Otukesh H, Sharifian M, Basiri A, Simforoush N, Hosseini R, Sedigh N, Golnari P, Rezaee M, Fereshtehnezhad M. Evaluation of Renal Graft Survival Rate in Children with Lower Urinary Tract Dysfunction in Labafi Nejad Hospital. Razi J Med Sci. 2006;13(51):17-23

    6.  Razzaghi-Azar M, Moghimi A, Sadigh N, Montazer M, Golnari P, Zahedi-Shulami L, Van Buuren S, Mohammad-Sadeghi H, Zanganeh-Kazemi A, Fereshtehnejad SM. Age at the Onset of Puberty and Menarche in Iranian Girls and Boys. Razi J Med Sci. 2006;13(50):71-82

    5.  Otukesh H, Sharifian M, Simfroosh N, Basiri A, Hoseini R, Sedigh N, Golnari P, Rezai M, Fereshtenejad M. Outcome of Renal Transplantation in Children with Lower Urinary Tract Abnormality. Transplant Proc. 2005;37(7):3071-3074

    4.  Otukesh H, Sharifian M, Basiri A, Simfroosh N, Hoseini R, Sedigh N, Golnari P, Rezai M, Fereshtenejad M. Mycophenolate mofetil in Pediatric Renal Transplantation. Transplant Proc. 2005;37(7):3012-3015

    3.  Ghasemi Sh, Golnari P, Hashemnejad M, Shahgholi N, Karimi P. Factors Influencing the Efficacy of Hepatitis B Vaccination in Patients Undergoing Hemodialysis. Razi J Med Sci. 2004;10(37):757-764

    2.  Ghasemi Sh, Golnari P, Chehrei A. Disseminated Nocardiosis in an Immunocompromised Child with Unknown Cause. Iran J Med Sci. 2002;27(3):147-150

    1.  Arjmandi-Rafsanjani Kh, Chehrei A, Chalian M, Fahimi A, Golnari P, Shojaei Sh. Factors Affecting the Survival Rate of Patients with Wilms’ Tumor. J Arak Uni Med Sci. 2002;5(3):30-35

    SKILLS

    A. Software

    3. Analytic: SPSS, STATA, SAS, R, RevMan, MedCalc
    2. Image management/processing: Centricity (GE), Syngo.via (Seimens), Vitrea (Canon), RAPID (iSchemaView)
    1. Other: Adobe Photoshop, REDCap, Epic EMR

    B. Database

    1. HCUP databases (NIS, NRD, NASS, etc), NSQIP, Vizient, SEER

    C. Language

    3. Native: Farsi (Persian)
    2. Advanced: English
    1. Basic: Arabic
